import {site} from '../content/site.mjs';
export const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escape;
export const arrow='<span aria-hidden="true">↗</span>';
const ui=(key,text)=>`data-ui="${key}"`;
export function head(title=site.name,description=site.description,path=''){
  return `<!doctype html><html lang="en" data-theme="${e(site.defaultTheme)}"><head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark"><meta name="theme-color" content="#f5f3ec">
  <meta name="description" content="${e(description)}"><meta name="author" content="${e(site.name)}">
  <meta property="og:type" content="website"><meta property="og:title" content="${e(title)}">
  <meta property="og:description" content="${e(description)}"><meta property="og:image" content="${e(site.url)}/assets/images/social.png">
  <meta property="og:url" content="${e(site.url)}/${path}"><meta name="twitter:card" content="summary_large_image">
  <link rel="canonical" href="${e(site.url)}/${path}"><link rel="icon" type="image/svg+xml" href="./assets/images/favicon.svg">
  <title>${e(title)} · INVARIANT</title><link rel="stylesheet" href="./assets/css/style.css">
  <script src="./assets/js/theme-init.js"></script></head><body>
  <a class="skip" href="#main">Skip to content</a>`;
}
export function header(home=true){const p=home?'':'./';return `<header class="header"><div class="shell header-inner">
  <a class="brand" href="${p}#top" aria-label="${e(site.name)} — home"><span class="brand-mark" aria-hidden="true">${e(site.initials)}<i></i></span><span class="brand-name">${e(site.name)}</span></a>
  <nav class="main-nav" aria-label="Main navigation"><a href="${p}#work" ${ui('navWork','')}>Work</a><a href="${p}#notes" ${ui('navNotes','')}>Notes</a><a href="${p}#lab" ${ui('navLab','')}>Playground<span class="nav-dot"></span></a><a href="${p}#about" ${ui('navAbout','')}>About</a></nav>
  <div class="header-actions"><button type="button" class="plain language-button" id="language-toggle" aria-label="Switch language">中</button><button type="button" class="icon-button" id="theme-toggle" aria-label="Toggle light and dark theme" title="Toggle theme"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.35" aria-hidden="true"><circle cx="12" cy="12" r="3.6"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg></button>${home?'<button class="command-trigger" id="command-trigger" type="button" aria-label="Open command menu"><span class="command-label">⌘</span><kbd>K</kbd></button>':''}</div>
  </div></header>`;}
export function footer(){return `<footer class="footer shell"><a class="footer-brand" href="#top">${e(site.initials)}<span class="small-dot"></span></a><p><span ${ui('footerText','')}>Built from a few first principles.</span> <a href="./colophon.html" ${ui('colophonLink','')}>Colophon ↗</a></p><span class="mono footer-end">INVARIANT / 01</span></footer>`;}
function learningArt(){let paths='';for(let i=0;i<9;i++){const r=26+i*12;paths+=`<ellipse cx="168" cy="105" rx="${r*1.3}" ry="${r*.62}" transform="rotate(-22 168 105)"/>`;}
return `<svg viewBox="0 0 360 210" fill="none" aria-hidden="true"><g class="contour">${paths}</g><path class="art-path" d="M49 172 C82 146 92 161 126 135 S175 143 191 109 S237 124 258 69 S293 72 310 40"/><circle class="art-point" cx="191" cy="109" r="4"/><circle class="art-point outline" cx="49" cy="172" r="3"/><path class="art-axis" d="M32 174v-126M32 174h296"/><text x="303" y="196">state</text><text x="43" y="37">π(a | s)</text></svg>`;}
function programArt(){return `<svg viewBox="0 0 360 210" fill="none" aria-hidden="true"><g class="art-axis"><path d="M46 107H110m54 0h34m54 0h54M137 82V47h90v35M137 131v34h90v-34"/><path d="m101 103 8 4-8 4m88-8 8 4-8 4m99-8 8 4-8 4"/></g><g class="art-node"><rect x="26" y="87" width="36" height="40" rx="2"/><rect x="110" y="82" width="54" height="50" rx="2"/><rect x="198" y="82" width="54" height="50" rx="2"/><rect x="302" y="87" width="36" height="40" rx="2"/></g><g class="art-notation"><text x="38" y="112">λ</text><text x="128" y="112">IR</text><text x="214" y="112">σ′</text><text x="314" y="112">→</text></g><circle class="art-point" cx="183" cy="47" r="3"/><text x="137" y="191">meaning → mechanism</text></svg>`;}
function systemArt(){let cells='';for(let r=0;r<5;r++)for(let c=0;c<8;c++)cells+=`<rect x="${129+c*20}" y="${48+r*23}" width="14" height="16" rx="1" class="${(r+c)%5===0?'cell-on':'cell-off'}"/>`;return `<svg viewBox="0 0 360 210" fill="none" aria-hidden="true"><path class="art-axis" d="M67 70h40v46h21m-60 21h25V86h34M288 58h24v109H103"/><rect class="art-node" x="35" y="51" width="55" height="38" rx="2"/><rect class="art-node" x="35" y="118" width="55" height="38" rx="2"/><text x="51" y="76">L1</text><text x="51" y="143">L2</text>${cells}<text x="180" y="189">locality / parallelism</text><circle class="art-point" cx="311" cy="109" r="3"/></svg>`;}
const arts={learning:learningArt,programs:programArt,systems:systemArt};
export function workCards(){return site.work.map(w=>`<article class="work-card" data-work="${e(w.id)}"><a class="card-link" href="./work-${e(w.id)}.html" data-detail="work:${e(w.id)}"><div class="work-art ${e(w.type)}">${arts[w.type]?.()||learningArt()}<span class="art-index mono">${e(w.number)} /</span></div><div class="work-copy"><div class="eyebrow card-kind">${e(w.en.label)}</div><h3>${e(w.en.title)} <span class="card-arrow" aria-hidden="true">↗</span></h3><p>${e(w.en.description)}</p><div class="tags">${w.tags.map(t=>`<span>${e(t)}</span>`).join('')}</div></div></a></article>`).join('');}
export function noteCards(){return site.notes.map((n,i)=>`<a class="note-row" href="./note-${e(n.id)}.html" data-detail="note:${e(n.id)}" data-note="${e(n.id)}"><span class="note-index mono">0${i+1}</span><div class="note-copy"><span class="eyebrow">${e(n.category)}</span><h3>${e(n.en.title)}</h3><p>${e(n.en.summary)}</p></div><span class="note-time mono">${e(n.read)}</span><span class="note-arrow" aria-hidden="true">↗</span></a>`).join('');}
export function home(){return head()+header()+`
<main id="main"><section class="hero shell" id="top" aria-labelledby="hero-title"><div class="hero-copy">
  <div class="eyebrow hero-eyebrow"><span class="small-dot"></span><span data-copy="role">${e(site.en.role)}</span></div>
  <h1 id="hero-title"><span data-hero-line="0">${e(site.en.heroLines[0])}</span><span data-hero-line="1">${e(site.en.heroLines[1])}</span><em data-hero-line="2">${e(site.en.heroLines[2])}</em></h1>
  <p class="hero-intro" data-copy="intro">${e(site.en.intro)}</p><p class="hero-sub" data-copy="subintro">${e(site.en.subintro)}</p>
  <div class="hero-links"><a class="button primary" href="#work"><span ${ui('exploreWork','')}>Explore my work</span><span aria-hidden="true">↗</span></a><a class="text-link" href="#lab"><span ${ui('openLab','')}>A little under the hood</span><span aria-hidden="true">↓</span></a></div>
</div><figure class="sculpture" id="sculpture"><div class="sculpture-top"><span class="eyebrow" ${ui('figureLabel','')}>FIG. 01 — CONTINUITY</span><span class="sculpture-number mono">ℝ³</span></div>
  <div class="sculpture-stage" id="sculpture-stage" role="img" aria-label="A rotating (2,3) torus knot, a continuous curve in three-dimensional space"><img class="sculpture-fallback" src="./assets/images/knot.svg" width="600" height="540" alt="A finely drawn (2,3) torus knot, a continuous curve in three-dimensional space."><canvas id="sculpture-canvas" aria-hidden="true"></canvas><div class="sculpture-cross cross-one">+</div><div class="sculpture-cross cross-two">+</div></div>
  <figcaption class="sculpture-bottom"><span><span class="figure-name" ${ui('knotName','')}>A continuous thread.</span><span class="mono figure-meta">T(2, 3) / <span id="render-backend">SVG</span></span></span><div class="sculpture-controls"><button type="button" class="icon-button" id="rotate-sculpture" aria-label="Rotate sculpture" title="Rotate">↻</button><button type="button" class="icon-button" id="motion-toggle" aria-label="Pause animation" aria-pressed="false" title="Pause / play">Ⅱ</button><a href="./colophon.html#geometry" class="icon-button inspect-button" aria-label="Read about the geometry" title="Inspect geometry">⌁</a></div></figcaption>
</figure></section>
<div class="index-strip shell"><span class="index-strip-label mono" ${ui('across','')}>A PRACTICE ACROSS</span><span><b>01</b> <span ${ui('disciplineLearning','')}>Learning</span></span><span><b>02</b> <span ${ui('disciplineSystems','')}>Systems</span></span><span><b>03</b> <span ${ui('disciplineFoundations','')}>Foundations</span></span><a href="${e(site.github)}" target="_blank" rel="noopener noreferrer">GitHub ${arrow}</a></div>
<section class="section shell" id="work" aria-labelledby="work-title"><div class="section-heading"><div><p class="eyebrow"><span class="section-num">01 /</span> <span ${ui('selectedWorkLabel','')}>SELECTED DIRECTIONS</span></p><h2 id="work-title" ${ui('workTitle','')}>Ideas, made tangible.</h2></div><p class="section-aside" ${ui('workAside','')}>Different layers.<br>The same curiosity.</p></div><div class="work-grid">${workCards()}</div></section>
<section class="lab-section" id="lab" aria-labelledby="lab-title"><div class="shell"><div class="section-heading"><div><p class="eyebrow"><span class="section-num">02 /</span> <span ${ui('labLabel','')}>THE PLAYGROUND</span></p><h2 id="lab-title" ${ui('labTitle','')}>A few things, understood by doing.</h2></div><p class="section-aside" ${ui('labAside','')}>Small experiments.<br>Real mechanisms.</p></div>
<div class="lab" id="lab-container"><div class="lab-topbar"><div class="lab-tabs" role="tablist" aria-label="Experiments"><button role="tab" type="button" aria-selected="true" aria-controls="panel-compiler" id="tab-compiler" data-lab="compiler">01 <span ${ui('compiler','')}>Compiler</span></button><button role="tab" type="button" aria-selected="false" aria-controls="panel-algebra" id="tab-algebra" data-lab="algebra" tabindex="-1">02 <span ${ui('algebra','')}>Algebra</span></button><button role="tab" type="button" aria-selected="false" aria-controls="panel-cache" id="tab-cache" data-lab="cache" tabindex="-1">03 <span ${ui('memory','')}>Memory</span></button><button role="tab" type="button" aria-selected="false" aria-controls="panel-scheduler" id="tab-scheduler" data-lab="scheduler" tabindex="-1">04 <span ${ui('scheduler','')}>Scheduler</span></button></div><span class="lab-status mono"><span class="small-dot"></span><span id="worker-status">LOCAL EXECUTION</span></span></div>
<div role="tabpanel" id="panel-compiler" aria-labelledby="tab-compiler" class="lab-panel"><div class="experiment-intro"><div><h3 ${ui('compilerTitle','')}>Meaning, preserved.</h3><p ${ui('compilerSubtitle','')}>Edit an expression. Inspect its representation. Run the machine code.</p></div><span class="experiment-badge mono">i32 → i32</span></div><div class="compiler-grid"><div class="editor-pane"><div class="pane-heading mono"><label for="source-code">PROGRAM.EXPR</label><button class="small-action" type="button" id="reset-code" ${ui('reset','')}>Reset</button></div><textarea id="source-code" maxlength="4096" spellcheck="false" aria-describedby="compiler-help">// A small program. A real compiler.
let a = input * 8;
let b = input * 8;
let unused = 12 * 3;
return a + b + 0;</textarea><div class="editor-controls"><label class="mono" for="compiler-input">input = <input type="number" id="compiler-input" value="7" min="-2147483648" max="2147483647" step="1"></label><button type="button" class="button lab-button" id="compile-button"><span ${ui('compile','')}>Compile & run</span> <span aria-hidden="true">↗</span></button></div></div><div class="output-pane"><div class="pane-heading"><div class="output-tabs" role="tablist" aria-label="Compiler output"><button role="tab" type="button" aria-selected="false" aria-controls="compiler-output" data-output="ir" id="output-tab-ir" tabindex="-1">IR</button><button role="tab" type="button" aria-selected="true" aria-controls="compiler-output" data-output="optimizedIR" id="output-tab-opt">OPTIMIZED</button><button role="tab" type="button" aria-selected="false" aria-controls="compiler-output" data-output="wat" id="output-tab-wasm" tabindex="-1">WASM</button></div><span class="output-indicator" aria-hidden="true"></span></div><pre id="compiler-output" role="tabpanel" aria-labelledby="output-tab-opt" tabindex="0"><code>// Run the compiler to inspect the result.</code></pre><div class="output-footer mono"><span id="compile-metric">SOURCE → AST → IR → WASM</span><button type="button" class="small-action" id="download-wasm" disabled>↓ .wasm</button></div></div></div><div class="lab-result"><span class="mono" ${ui('result','')}>RESULT</span><strong id="compiler-result">—</strong><span class="result-detail mono" id="compiler-detail">—</span><span class="compile-message" id="compile-message" role="status" aria-live="polite"></span></div><p class="lab-footnote" id="compiler-help" ${ui('compilerHelp','')}>Pure, wrapping i32 arithmetic. No eval. An actual Wasm binary, generated and executed in your browser. Ctrl / ⌘ + Enter to run.</p></div>
<div role="tabpanel" id="panel-algebra" aria-labelledby="tab-algebra" class="lab-panel" hidden><div class="experiment-intro"><div><h3 ${ui('algebraTitle','')}>Order is a structure.</h3><p ${ui('algebraSubtitle','')}>Compose two generators. Explore all six symmetries.</p></div><span class="experiment-badge mono">S₃</span></div><div class="algebra-grid"><div class="group-visual"><svg id="cayley-graph" viewBox="0 0 480 300" role="img" aria-label="Cayley graph of S3; a edges are solid, b edges are dashed."></svg><div class="graph-legend mono"><span>— a = (123)</span><span>┄ b = (12)</span></div></div><div class="group-controls"><div class="group-state"><span class="eyebrow" ${ui('currentElement','')}>CURRENT ELEMENT</span><strong id="group-element" aria-live="polite">e</strong><span class="mono" id="group-permutation">[1, 2, 3]</span></div><div class="generator-buttons"><button type="button" class="button lab-button" id="group-a">∘ a <span ${ui('rotate','')}>Rotate</span></button><button type="button" class="button lab-button secondary-lab" id="group-b">∘ b <span ${ui('swap','')}>Swap</span></button><button type="button" class="small-action" id="group-reset" ${ui('reset','')}>Reset</button></div><p class="mono group-law">a³ = e &nbsp; b² = e &nbsp; ab ≠ ba</p><div class="group-check mono" id="group-check" role="status"></div></div></div><details class="group-table-details"><summary ${ui('multiplicationTable','')}>Inspect the multiplication table</summary><div id="group-table"></div></details><p class="lab-footnote" ${ui('algebraHelp','')}>Right multiplication: state ← state ∘ generator. The rightmost permutation acts first. Table and relations are computed from permutations.</p></div>
<div role="tabpanel" id="panel-cache" aria-labelledby="tab-cache" class="lab-panel" hidden><div class="experiment-intro"><div><h3 ${ui('cacheTitle','')}>Same data. Different journey.</h3><p ${ui('cacheSubtitle','')}>A memory-access trace, one cache line at a time.</p></div><span class="experiment-badge mono">16 × 16</span></div><div class="model-controls"><label><span ${ui('traversal','')}>Traversal</span><select id="cache-order"><option value="row">Row-major walk</option><option value="column">Column-major walk</option><option value="blocked">Blocked 4 × 4 walk</option></select></label><label><span ${ui('lineSize','')}>Elements / line</span><select id="cache-size"><option>2</option><option selected>4</option><option>8</option><option>16</option></select></label><button class="button lab-button" id="cache-play" type="button" ${ui('playTrace','')}>Play trace</button></div><div class="cache-grid"><div><div class="pane-heading mono">ROW-MAJOR MEMORY <span id="cache-address">ADDRESS —</span></div><div class="memory-matrix" id="memory-matrix" aria-label="Matrix memory-access visualization"></div></div><div><div class="pane-heading mono">DIRECT-MAPPED CACHE / 8 LINES</div><div class="cache-lines" id="cache-lines"></div><div class="model-metrics"><div><span ${ui('hits','')}>Hits</span><strong id="cache-hits">0</strong></div><div><span ${ui('misses','')}>Misses</span><strong id="cache-misses">0</strong></div><div><span ${ui('hitRate','')}>Hit rate</span><strong id="cache-rate">—</strong></div></div></div></div><div class="trace-scrubber"><label for="cache-step" class="mono" id="cache-step-label">ACCESS 0 / 256</label><input type="range" id="cache-step" min="0" max="256" value="0"><button type="button" class="small-action" id="cache-next" ${ui('step','')}>Step →</button></div><p class="lab-footnote" ${ui('cacheHelp','')}>Educational model, not a hardware benchmark. Cold cache, direct mapping, no prefetching; line size is measured in matrix elements.</p></div>
<div role="tabpanel" id="panel-scheduler" aria-labelledby="tab-scheduler" class="lab-panel" hidden><div class="experiment-intro"><div><h3 ${ui('schedulerTitle','')}>A little time for everyone.</h3><p ${ui('schedulerSubtitle','')}>Round-robin scheduling, with the policy made visible.</p></div><span class="experiment-badge mono">RR</span></div><div class="model-controls"><label for="quantum"><span ${ui('timeQuantum','')}>Time quantum</span><input type="range" id="quantum" min="1" max="6" value="2"><output for="quantum" id="quantum-value" class="mono">2 ticks</output></label><span class="mono jobs-description">A (0,7) &nbsp; B (1,4) &nbsp; C (2,6)<br><small>(arrival, burst)</small></span></div><div id="scheduler-timeline" class="scheduler-timeline" aria-label="Round-robin scheduling timeline"></div><div id="scheduler-stats" class="scheduler-stats"></div><p class="lab-footnote" ${ui('schedulerHelp','')}>Single CPU; integer ticks; no I/O or context-switch cost. New arrivals enter the ready queue before the running job is requeued.</p></div>
</div><noscript><p>The experiments require JavaScript. All research descriptions and notes remain available without it.</p></noscript></div></section>
<section class="section shell notes-section" id="notes" aria-labelledby="notes-title"><div class="section-heading"><div><p class="eyebrow"><span class="section-num">03 /</span> <span ${ui('notesLabel','')}>FIELD NOTES</span></p><h2 id="notes-title" ${ui('notesTitle','')}>Things worth thinking through.</h2></div><p class="section-aside" ${ui('notesAside','')}>Not answers to everything.<br>Better questions, perhaps.</p></div><div class="note-list">${noteCards()}</div></section>
<section class="about-section shell" id="about" aria-labelledby="about-title"><div class="about-aside"><span class="eyebrow"><span class="section-num">04 /</span> <span ${ui('aboutLabel','')}>A LITTLE CONTEXT</span></span><div class="about-monogram" aria-hidden="true">${e(site.initials)}<span>.</span></div><span class="mono about-caption">LEARN / BUILD / UNDERSTAND</span></div><div class="about-copy"><h2 id="about-title" data-copy="aboutTitle">${e(site.en.aboutTitle)}</h2><p data-copy="about">${e(site.en.about)}</p><blockquote data-copy="philosophy">${e(site.en.philosophy)}</blockquote><div class="about-links"><a href="${e(site.github)}" target="_blank" rel="noopener noreferrer">GitHub ${arrow}</a>${site.scholar?`<a href="${e(site.scholar)}" target="_blank" rel="noopener noreferrer">Google Scholar ${arrow}</a>`:''}${site.cv?`<a href="${e(site.cv)}">CV ↓</a>`:''}</div></div></section>
<section class="contact-section shell" id="contact"><div><p class="eyebrow" ${ui('contactLabel','')}>LET’S COMPARE NOTES</p><h2 data-copy="contact">${e(site.en.contact)}</h2><p data-copy="contactSub">${e(site.en.contactSub)}</p></div><a class="contact-link" href="${site.email?'mailto:'+e(site.email):e(site.github)}" ${site.email?'':'target="_blank" rel="noopener noreferrer"'}>${site.email?e(site.email):'Find me on GitHub'} <span aria-hidden="true">↗</span></a></section></main>${footer()}
<dialog id="detail-dialog" class="detail-dialog"><div class="dialog-top"><span class="eyebrow" id="detail-category">FIELD NOTES</span><button type="button" class="icon-button close-dialog" aria-label="Close article">×</button></div><div id="detail-content" class="reading-content"></div></dialog>
<dialog id="command-dialog" class="command-dialog" aria-labelledby="command-title"><h2 id="command-title" class="sr-only">Command menu</h2><div class="command-input-wrap"><span class="mono" aria-hidden="true">&gt;_</span><input id="command-input" type="search" placeholder="Where would you like to go?" autocomplete="off" aria-label="Search commands" aria-controls="command-results" aria-autocomplete="list" role="combobox" aria-expanded="true"><button type="button" class="small-action close-dialog" aria-label="Close command menu">esc</button></div><div id="command-results" role="listbox" aria-label="Commands"></div><div class="command-footer mono"><span>↑ ↓ <span ${ui('navigate','')}>navigate</span></span><span>↵ <span ${ui('select','')}>select</span></span><span ${ui('commandHint','')}>A menu, not a pretend shell.</span></div></dialog>
<div class="toast" id="toast" role="status" aria-live="polite"></div><script type="module" src="./assets/js/app.js"></script></body></html>`;}
export function article(item,kind){const n=item.en;const body=n.paragraphs||n.detail;const path=`${kind}-${item.id}.html`;return head(n.title,n.summary||n.description,path)+header(false)+`<main class="article-page shell" id="main"><a class="text-link" href="./#${kind==='note'?'notes':'work'}">← <span ${ui('backHome','')}>Back to home</span></a><article data-article-kind="${kind}" data-article-id="${e(item.id)}"><p class="eyebrow article-category">${e(item.category||n.label)}</p><h1>${e(n.title)}</h1><p class="article-lede">${e(n.summary||n.description)}</p><div class="reading-content" id="article-body">${body.map(p=>`<p>${e(p)}</p>`).join('')}${n.code?`<pre><code>${e(n.code)}</code></pre>`:''}</div></article><a class="button primary" href="./#lab"><span ${ui('tryLab','')}>Try the experiments</span> ↗</a></main>${footer()}<script type="module" src="./assets/js/app.js"></script></body></html>`;}
export function colophon(){return head('Colophon','The design, geometry and mechanisms behind INVARIANT.','colophon.html')+header(false)+`<main class="article-page shell" id="main"><a class="text-link" href="./">← Home</a><p class="eyebrow">DESIGN / IMPLEMENTATION</p><h1>Nothing here<br>is a pretend machine.</h1><p class="article-lede">A small website, made from a few carefully chosen primitives.</p><div class="reading-content"><h2 id="geometry">01 / A continuous thread</h2><p>The hero is a (2,3) torus knot. Its centerline is c(t) = ((2 + cos 3t) cos 2t, (2 + cos 3t) sin 2t, sin 3t), with t ∈ [0,2π]. A narrow tube is swept around this curve using a local orthonormal frame. The surface grid follows the parameterization.</p><p>The renderer first tries native WebGPU with a WGSL shader. If that path is unavailable, it tries WebGL2 with GLSL; if both fail, the pre-rendered SVG remains. There are no external models, textures, fonts, or graphics libraries. Motion pauses when off-screen, in a hidden tab, or when reduced motion is requested.</p><h2>02 / A compiler, not a recording</h2><p>The compiler is written in dependency-free JavaScript. It parses a deliberately bounded, pure i32 expression language, lowers to SSA-like IR, optimizes, emits a valid Wasm binary, and instantiates it inside a dedicated Worker. The Wasm module imports nothing, exports only compute, and contains no loops or memory access. If Wasm is unavailable, an explicitly labeled interpreter fallback preserves the example.</p><h2>03 / Models with boundaries</h2><p>The S₃ table is constructed from permutations; all 216 associativity triples are checked. The cache is a cold, direct-mapped teaching model. The scheduler is round robin with zero context-switch cost. These models illustrate mechanisms; they do not benchmark the visitor’s hardware.</p><h2>04 / Interface before spectacle</h2><p>Real links work without JavaScript. Notes have standalone pages. Native dialogs preserve keyboard focus. There is no custom cursor, scroll hijacking, sound, tracking script, third-party font request, or skill-percentage chart. Light and dark modes, a command menu, Chinese and English content, and a motion toggle are ordinary controls, not Easter eggs.</p><h2>05 / Edit & deploy</h2><p>Public content lives in <code>content/site.mjs</code>. Design tokens live in <code>assets/css/style.css</code>. Run <code>npm run build</code> to regenerate the static pages; no package installation is required. The repository root or the generated <code>dist/</code> directory can be served as static files. GitHub Pages supplies hosting; all computation described here happens in the browser.</p><h2>Source map</h2><pre>assets/js/sculpture.js   → WebGPU / WebGL2 renderer
assets/js/core/compiler.js → parser, IR, optimizer, Wasm emitter
assets/js/core/algebra.js  → permutation composition and checks
assets/js/core/systems.js  → cache and scheduling models
assets/js/worker.js        → experiment execution
assets/js/lab.js           → experiment interfaces
tests/core.test.mjs        → executable checks</pre><p>The implementation is distributed under the MIT license. Research cards are editable direction descriptions, not invented publications. Add verified bibliographic details and your own contact information before publishing.</p><p><a href="./README.zh-CN.md">中文使用说明 ↗</a> · <a href="./assets/js/core/compiler.js">Read the compiler source ↗</a></p></div></main>${footer()}<script type="module" src="./assets/js/app.js"></script></body></html>`;}
